# More information about the configuration file can be found at:
#     https://alacritty.org/config-alacritty.html

# catppuccin-macchiato them taken from:
#     https://github.com/catppuccin/alacritty
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]
working_directory = "/Users/cle126/Developer"

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
# brew install --cask font-hack-nerd-font
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 14

[font.offset]
x = 0
y = 7

[window]
position = { x = 0, y = 0 }
dimensions = { columns = 200, lines = 60 }
decorations = "transparent"
dynamic_padding = true
decorations_theme_variant = "Dark"
option_as_alt = "None"
opacity = 0.8
blur = true
startup_mode = "Windowed"
padding = { x = 10, y = 20 }

[cursor]
style = { shape = "Underline" }
