# --- History ---
setopt HIST_IGNORE_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS

# --- fpath ---
# All fpath modifications must happen before compinit.
# ~/.cache/zsh-completions holds tool-native completions generated by
# `<tool> completion zsh`; regenerate with `make completions`.
fpath=(
  ~/.zsh/completions
  ~/.cache/zsh-completions
  ~/.zsh/functions
  $fpath
)
autoload -Uz git-aliases take ssh-terminfo

# --- Completion ---
# compaudit is slow (~25ms). Run a full compinit only if the zcompdump is
# older than 24h; otherwise skip the audit with -C.
zstyle ':completion:*' menu select
autoload -Uz compinit
if [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+24) ]]; then
  compinit
else
  compinit -C
fi

# --- Homebrew prefix ---
# Detect Homebrew/Linuxbrew location so the rest of the file can reference
# $HOMEBREW_PREFIX instead of hardcoding /opt/homebrew. `brew shellenv`
# normally sets this, but we avoid the subprocess to keep startup fast.
if [[ -z "$HOMEBREW_PREFIX" ]]; then
  if [[ -d /opt/homebrew ]]; then
    export HOMEBREW_PREFIX=/opt/homebrew
  elif [[ -d /home/linuxbrew/.linuxbrew ]]; then
    export HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
  fi
fi

# --- Plugins ---
# Load antidote early so `_evalcache` (mroth/evalcache) is available for the
# tool integrations below. Order in plugins.txt matters:
#   evalcache           — must come first
#   zsh-autosuggestions — widget-registering; before syntax-highlighting
#   zsh-syntax-highlighting — must be last
export ZSH_AUTOSUGGEST_DEBOUNCE_TIME=50
export ZSH_AUTOSUGGEST_USE_ASYNC="true"
if [[ -n "$HOMEBREW_PREFIX" && -f "$HOMEBREW_PREFIX/opt/antidote/share/antidote/antidote.zsh" ]]; then
  source "$HOMEBREW_PREFIX/opt/antidote/share/antidote/antidote.zsh"
elif [[ -f "$HOME/.antidote/antidote.zsh" ]]; then
  source "$HOME/.antidote/antidote.zsh"
fi
antidote load ~/.zsh/plugins.txt

# --- Paths ---
# Make PATH idempotent against `exec zsh` chains and hostile inherited PATHs.
# `typeset -U` on both the PATH scalar and the path array catches both
# `export PATH="$PATH:..."` and `path=(...)` style assignments. The hard
# reset to a canonical baseline guarantees /usr/local/bin wins on shared VMs
# (e.g. gen3-*) where /etc/environment puts it last and apt's old fzf would
# otherwise shadow bootstrap.sh's pinned fzf 0.68.
typeset -U PATH path cdpath fpath manpath
path=(/usr/local/bin /usr/local/sbin /usr/sbin /usr/bin /sbin /bin)

# Postgres CLI/headers — only wired up when the brew keg is installed.
if [[ -n "$HOMEBREW_PREFIX" && -d "$HOMEBREW_PREFIX/opt/postgresql@16" ]]; then
  export PATH="$HOMEBREW_PREFIX/opt/postgresql@16/bin:$PATH"
  export LDFLAGS="-L$HOMEBREW_PREFIX/opt/postgresql@16/lib"
  export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/postgresql@16/include"
fi
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/go/bin"

# --- Version manager ---
# Shims-only mode: adding mise's shim dir to PATH is all `mise activate
# --shims` actually does for us — tool version resolution happens at
# invocation via the shims reading mise.toml/.tool-versions. We do it
# manually instead of via `_evalcache mise activate` because mise activate
# also prepends /usr/bin defensively, which shadows /usr/local/bin and
# breaks bootstrap.sh's pinned binaries (e.g. fzf 0.68 vs apt's 0.29).
# Tradeoff (same as before): mise's `[env]` per-project env-var injection
# is not applied; switch to full `mise activate zsh` if you need it.
path=("$HOME/.local/share/mise/shims" $path)

# --- Terminal ---
# Only set TERM=ghostty if this machine actually has ghostty's terminfo
# entry — otherwise curses-based programs will error with "unknown terminal".
(( $+commands[infocmp] )) && infocmp ghostty &>/dev/null && export TERM=ghostty

# --- Tool integrations ---
# fzf: fd for listing (respects .gitignore, hides .git), bat/eza previews
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:500 {}'"
export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always --level=2 {}'"
_evalcache fzf --zsh

_evalcache zoxide init zsh

# Colorized man pages via bat
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

[ -f "$HOME/.config/op/plugins.sh" ] && source "$HOME/.config/op/plugins.sh"
[ -f "$HOME/.config/fabric/fabric-bootstrap.inc" ] && . "$HOME/.config/fabric/fabric-bootstrap.inc"

# --- Aliases ---
alias cat=bat
alias zshrc="nvim ~/.zshrc"
alias zshrcs="source ~/.zshrc"
alias l="eza -l --icons --git -a"
alias lt="eza --tree --level=2 --long --icons --git"
alias ltree="eza --tree --level=2 --icons --git"
alias ol="ollama run llama3.1"

# --- Prompt ---
_evalcache starship init zsh

# --- Key bindings ---
source ~/.zsh/keybindings.zsh
