# --- History ---
setopt HIST_IGNORE_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS

# --- fpath ---
# All fpath modifications must happen before compinit.
# ~/.cache/zsh-completions holds tool-native completions generated by
# `<tool> completion zsh`; regenerate with `make completions`.
fpath=(
  ~/.zsh/completions
  ~/.cache/zsh-completions
  ~/.zsh/functions
  $fpath
)
autoload -Uz git-aliases take

# --- Completion ---
# compaudit is slow (~25ms). Run a full compinit only if the zcompdump is
# older than 24h; otherwise skip the audit with -C.
zstyle ':completion:*' menu select
autoload -Uz compinit
if [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+24) ]]; then
  compinit
else
  compinit -C
fi

# --- Plugins ---
# Load antidote early so `_evalcache` (mroth/evalcache) is available for the
# tool integrations below. Order in plugins.txt matters:
#   evalcache           — must come first
#   zsh-autosuggestions — widget-registering; before syntax-highlighting
#   zsh-syntax-highlighting — must be last
export ZSH_AUTOSUGGEST_DEBOUNCE_TIME=50
export ZSH_AUTOSUGGEST_USE_ASYNC="true"
source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
antidote load ~/.zsh/plugins.txt

# --- Paths ---
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/postgresql@16/lib"
export CPPFLAGS="-I/opt/homebrew/opt/postgresql@16/include"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/go/bin"

# --- Version manager ---
# `--shims` is dramatically faster than full activation: it only adds the
# shim dir to PATH, with no chpwd hook. Tool version resolution still works
# per-directory via shims reading mise.toml/.tool-versions at invocation.
# Tradeoff: mise's `[env]` per-project env-var injection does not apply.
_evalcache mise activate zsh --shims

# --- Terminal ---
export TERM=ghostty

# --- Tool integrations ---
# fzf: fd for listing (respects .gitignore, hides .git), bat/eza previews
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:500 {}'"
export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always --level=2 {}'"
_evalcache fzf --zsh

_evalcache zoxide init zsh

# Colorized man pages via bat
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

[ -f "$HOME/.config/op/plugins.sh" ] && source "$HOME/.config/op/plugins.sh"
[ -f "$HOME/.config/fabric/fabric-bootstrap.inc" ] && . "$HOME/.config/fabric/fabric-bootstrap.inc"

# --- Aliases ---
alias cat=bat
alias zshrc="nvim ~/.zshrc"
alias zshrcs="source ~/.zshrc"
alias l="eza -l --icons --git -a"
alias lt="eza --tree --level=2 --long --icons --git"
alias ltree="eza --tree --level=2 --icons --git"
alias ol="ollama run llama3.1"

# --- Prompt ---
_evalcache starship init zsh

# --- Key bindings ---
source ~/.zsh/keybindings.zsh
