# --- History ---
setopt HIST_IGNORE_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS

# --- fpath ---
# All fpath modifications must happen before compinit.
# ~/.cache/zsh-completions holds tool-native completions generated by
# `<tool> completion zsh`; regenerate with `make completions`.
fpath=(
  ~/.zsh/completions
  ~/.cache/zsh-completions
  ~/.zsh/functions
  $fpath
)
autoload -Uz git-aliases

# --- Completion ---
zstyle ':completion:*' menu select
autoload -Uz compinit
compinit

# --- Paths ---
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export JAVA_HOME=$(/usr/libexec/java_home)
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/postgresql@16/lib"
export CPPFLAGS="-I/opt/homebrew/opt/postgresql@16/include"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"

# --- Version managers ---
eval "$(mise activate zsh)"
export PATH="$PATH:$(go env GOPATH)/bin"

# --- Terminal ---
export TERM=ghostty

# --- Tool integrations ---
# fzf: fd for listing (respects .gitignore, hides .git), bat/eza previews
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:500 {}'"
export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always --level=2 {}'"
source <(fzf --zsh)

eval "$(zoxide init zsh)"
eval "$(thefuck --alias)"

# Colorized man pages via bat
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

if [ -f "$HOME/Developer/google.cloud/google-cloud-sdk/path.zsh.inc" ]; then
  . "$HOME/Developer/google.cloud/google-cloud-sdk/path.zsh.inc"
fi
if [ -f "$HOME/Developer/google.cloud/google-cloud-sdk/completion.zsh.inc" ]; then
  . "$HOME/Developer/google.cloud/google-cloud-sdk/completion.zsh.inc"
fi

[ -f "$HOME/.config/op/plugins.sh" ] && source "$HOME/.config/op/plugins.sh"
[ -f "$HOME/.config/fabric/fabric-bootstrap.inc" ] && . "$HOME/.config/fabric/fabric-bootstrap.inc"

# --- Aliases ---
alias cat=bat
alias zshrc="nvim ~/.zshrc"
alias zshrcs="source ~/.zshrc"
alias l="eza -l --icons --git -a"
alias lt="eza --tree --level=2 --long --icons --git"
alias ltree="eza --tree --level=2 --icons --git"
alias ol="ollama run llama3.1"

# --- Prompt ---
eval "$(starship init zsh)"

# --- Plugins ---
# Antidote loads plugins in the order listed in plugins.txt.
# zsh-syntax-highlighting must load last; keep it at the end of that file.
export ZSH_AUTOSUGGEST_DEBOUNCE_TIME=50
export ZSH_AUTOSUGGEST_USE_ASYNC="true"
source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
antidote load ~/.zsh/plugins.txt

# --- Key bindings ---
source ~/.zsh/keybindings.zsh
